from fastapi import APIRouter
from .endpoints import health, employees, machines, orders, tasks, production, telemetry, maintenance, incidents, profile, imports, ai, memory, users, notifications, reports, plans, smart_split, assistant, worker_auth, allocation, voice, worker, resolve, commands, factories, onboarding, what_if

api_router = APIRouter()

api_router.include_router(health.router, prefix="/health", tags=["health"])
api_router.include_router(factories.router, prefix="/factories", tags=["factories"])
api_router.include_router(onboarding.router, prefix="/onboarding", tags=["onboarding"])
api_router.include_router(employees.router, prefix="/employees", tags=["employees"])
api_router.include_router(machines.router, prefix="/machines", tags=["machines"])
api_router.include_router(orders.router, prefix="/orders", tags=["orders"])
api_router.include_router(tasks.router, prefix="/tasks", tags=["tasks"])
api_router.include_router(production.router, prefix="/production", tags=["production"])
api_router.include_router(telemetry.router, prefix="/telemetry", tags=["telemetry"])
api_router.include_router(maintenance.router, prefix="/maintenance", tags=["maintenance"])
api_router.include_router(incidents.router, prefix="/incidents", tags=["incidents"])
api_router.include_router(profile.router, prefix="/profile", tags=["profile"])
api_router.include_router(imports.router, prefix="/import", tags=["import"])
api_router.include_router(ai.router, prefix="/ai", tags=["ai"])
api_router.include_router(memory.router, prefix="/memory", tags=["memory"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(plans.plans, prefix="/plans", tags=["plans"])
api_router.include_router(plans.assignments, prefix="/assignments", tags=["assignments"])
api_router.include_router(plans.tokens, prefix="/push-tokens", tags=["push"])
api_router.include_router(smart_split.router, prefix="/ai", tags=["smart-split"])
api_router.include_router(assistant.router, prefix="/ai/assistant", tags=["assistant"])
api_router.include_router(worker_auth.router, prefix="/worker-auth", tags=["worker-auth"])
api_router.include_router(allocation.router, prefix="/allocation", tags=["allocation"])
api_router.include_router(voice.router, prefix="/voice", tags=["voice"])
api_router.include_router(worker.router, prefix="/worker", tags=["worker"])
api_router.include_router(resolve.router, prefix="/resolve", tags=["resolve"])
api_router.include_router(commands.router, prefix="/ai/commands", tags=["commands"])
api_router.include_router(what_if.router, prefix="/what-if", tags=["what-if"])
